/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal project creation.
// Keep it committed so TypeScript can resolve Next.js types before first install.
